name: Fix Environment Variables

on:
  workflow_dispatch: # Manual trigger

jobs:
  fix-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Fix .env file
        run: |
          cat > .env << EOF
          GITHUB_TOKEN=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
          GIST_ID=bd044441c90c6789bfa8c7b730b09226
          EOF
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .env
          git commit -m "Fix environment variables"
          git push
